apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tensorflow-deployment
  labels:
    app: tensorflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow
        image: gcr.io/tensorflow/tensorflow
        ports:
         - containerPort: 8888
           protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: tf-service
spec:
  selector:
    app: tensorflow
  ports:
   - protocol: TCP
     port: 8888 
     targetPort: 8888
     name: httpport
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: tf-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
     - hosts: 
       - "tf.fancy.cloud"
       secretName:  tls-fancy 
  rules:
  - host: tf.fancy.cloud
    http:
     paths:
     - path: / 
       backend:
         serviceName: tf-service
         servicePort: httpport 
---

